# Generated by Django 4.1.13 on 2023-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='tag_department',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
